### ISSUE TITLE
bug: Minor Spelling error

### ISSUE THREAD

**Issue by PI-Gorbo** [lucasteles/FSharp.MinimalApi#38]
Heyo! Love the library and am really enjoying the DX provided.
Just found one thing:
In `EndpointsBuilder.fs` the overload of the requireAuthorization method that takes in one policy has a spelling error 
```
    [<CustomOperation("requireAthorization")>]
    member _.RequireAuth(state, policy: AuthorizationPolicy) =
        { state with
            MapFn = state.MapFn >> (fun e -> e.RequireAuthorization(policy)) }
```

Thanks for the awesome library.
Im interested in helping / contributing if you need any help!

**Comment by lucasteles** [comment]
Oh, I see 😅
